"""user add tokens

Revision ID: 930e966e0191
Revises: deb3792f1abb
Create Date: 2018-11-18 18:24:29.345896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930e966e0191'
down_revision = 'deb3792f1abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
